server:
  port: ${RESOURCE_SERVER_PORT}

spring:
  web:
    resources:
      add-mappings: false

  datasource:
    url: ${RESOURCE_DB_URL}
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${RESOURCE_DB_USERNAME}
    password: ${RESOURCE_DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

grpc:
  server:
    port: ${RESOURCE_GRPC_PORT}

auth:
  server:
    url: ${AUTH_GRPC_SERVER_URL}
    port: ${AUTH_GRPC_SERVER_PORT}

jwt:
  access:
    header: ${JWT_ACCESS_TOKEN_HEADER}
  header:
    format: ${JWT_HEADER_FORMAT}