server:
  port: ${AUTH_SERVER_PORT}

grpc:
  server:
    port: ${AUTH_GRPC_PORT}

spring:
  web:
    resources:
      add-mappings: false

  datasource:
    url: ${AUTH_DB_URL}
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${AUTH_DB_USERNAME}
    password: ${AUTH_DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect


jwt:
  secretKey: ${JWT_SECRET_KEY}
  header:
    format: ${JWT_HEADER_FORMAT}
  access:
    expiration: ${JWT_ACCESS_TOKEN_EXPIRE_TIME}
    header: ${JWT_ACCESS_TOKEN_HEADER}
  refresh:
    expiration: ${JWT_REFRESH_TOKEN_EXPIRE_TIME}