#!/bin/sh

# Git의 루트 디렉토리를 찾음
PROJECT_ROOT=$(git rev-parse --show-toplevel)

# 현재 스테이징된 파일 목록을 가져옴
stagedFiles=$(git diff --staged --name-only)

# 프로젝트 디렉토리 정의
AUTH_DIR="$PROJECT_ROOT/keumbang-auth"
RESOURCE_DIR="$PROJECT_ROOT/keumbang-resource"

# keumbang-auth 디렉토리의 파일이 스테이징된 경우, spotlessApply 실행
if echo "$stagedFiles" | grep -q "^keumbang-auth/"; then
    echo "Running spotlessApply for auth..."
    cd "$AUTH_DIR" && ./gradlew spotlessApply

    if [ $? -ne 0 ]; then
        echo "Spotless apply failed for auth!"
        exit 1
    fi
fi

# keumbang-resource 디렉토리의 파일이 스테이징된 경우, spotlessApply 실행
if echo "$stagedFiles" | grep -q "^keumbang-resource/"; then
    echo "Running spotlessApply for resource..."
    cd "$RESOURCE_DIR" && ./gradlew spotlessApply

    if [ $? -ne 0 ]; then
        echo "Spotless apply failed for resource!"
        exit 1
    fi
fi

# 포맷팅 후 변경된 파일을 다시 Git에 추가
for file in $stagedFiles; do
    if test -f "$file"; then
        git add "$file"
    fi
done

echo "Pre-commit hook completed successfully."
exit 0